### ISSUE TITLE
Incorrect solution in Basic Training > Configuration > Config params

### ISSUE THREAD

**Issue by alanzos** [nextflow-io/training#295]
Hi, I was watching the Community Foundational Nextflow Training - Session 1 and I noticed that a solution is not correct on this section:
https://training.nextflow.io/basic_training/config/#config-params

The output of "nextflow run params.nf" is "Hello world!", but the solution is "Bonjour le monde!".
That solution would be correct if the command would have been "nextflow run params.nf -c myconfig.config"

And similar error with the second solution, the correct output is "Hola world!".
The second solution would be correct if the command would have been "nextflow run params.nf -c myconfig.config --foo Hola"

It would be great if these two points could be corrected.

Thanks for the great tutorial and video!

**Comment by mribeirodantas** [comment]
Hello, @alanzos !

If you read the instructions carefully, you'll see it's asked to name the content of the first code block `nextflow.config`. That's why we don't need to provide it with `-c`, as the `nextflow.config` file in the current directory is automatically loaded by Nextflow. I agree with you that, if the configuration file wasn't said to be named `nextflow.config`, we'd need to load it with `-c`, but it is not the case. Please, check the printscreen below for the instructions provided in the training material.

<img width="780" alt="Captura de Tela 2023-12-20 às 01 53 29" src="https://github.com/nextflow-io/training/assets/1023197/64acb617-0b29-4276-8fad-83723c800162">
